### ISSUE TITLE
Create a latest image tag

### ISSUE THREAD

**Issue by buzzke** [onedr0p/exportarr#1]
I got some issues with the docker-compose

1. First issue with Enable Quality = True
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.sonarr-exporter.environment.ENABLE_EPISODE_QUALITY_METRICS **contains true**, which is an invalid type, it should be a string, number, or a null

2. Second issue with Enable Quality = false
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.sonarr-exporter.environment.ENABLE_EPISODE_QUALITY_METRICS **contains false**, which is an invalid type, it should be a string, number, or a null

3. The manifest was also not found
 Pulling sonarr-exporter (onedr0p/exportarr:latest)...
**ERROR: manifest for onedr0p/exportarr:latest not found**

**Comment by onedr0p** [comment]
Hi @buzzke! 

For 1 and 2 quote the boolean, like "false". I'll update the compose example.

For number 3, I have not created a latest image yet, please use the latest tagged version. I plan to have a latest tag once I figure out how to do it in Github Actions.

`onedr0p/exportarr:v0.3.0`

**Comment by onedr0p** [comment]
I have update the compose examples and rename this issue to reflect the task of creating a latest image.

**Comment by buzzke** [comment]
Worked with tag: master
Also changed the docker-compose to reflect the changes.
