### ISSUE TITLE
Exportarr on docker swarm

### ISSUE THREAD

**Issue by margaale** [onedr0p/exportarr#10]
I've been trying to get exportarr working within a stack in my swarm. This is the snippet of the docker-compose.yml

`    
     ...
     radarr_exporter:
     image: onedr0p/exportarr:master
     command: ["exportarr", "radarr"]
     environment:
         PORT: 9811
         URL: "http://radarr:7878"
         APIKEY: ""
     depends_on:
         - radarr
     networks:
         - radarr
         - monitor
     deploy:
         replicas: 1
    ...
`

The container starts and dies and all i get in the log is: No help topic for 'exportarr'
Could you give me a hint on whats going on? At first i thought that command is not taken into account while deploying the stack but i couldn't find that info on the docker reference.

Thanks

**Comment by onedr0p** [comment]
I don't run this in Docker swarm but can you set the image to the release version?

- `onedr0p/exportarr:v0.3.2`

Also posting the exact error log and a properly formatted yaml may help me help you.

**Comment by margaale** [comment]
I'll try the changes, but there is no tag 0.3.2 in dockerhub: https://hub.docker.com/r/onedr0p/exportarr/tags

I'm using master instead

**Comment by onedr0p** [comment]
Oh nice catch, not sure why that tag didn't trigger a Docker image. I'll try to publish a new release.

**Comment by onedr0p** [comment]
`onedr0p/exportarr:v0.3.3` is now available

**Comment by margaale** [comment]
Yep, now it's working fine with the change in the command. Thanks

**Comment by onedr0p** [comment]
Great!

**Comment by margaale** [comment]
Updated my comment since i found out how to do it
