### ISSUE TITLE
sonarr_episode_quality_total missing in sonarr metrics

### ISSUE THREAD

**Issue by Y0ngg4n** [onedr0p/exportarr#104]
# Details

**What steps did you take and what happened:**

I have checked the metrics endpoint for sonarr.
There was the sonarr_episode_quality_total missing

**What did you expect to happen:**

sonarr_episode_quality_total existing

**Comment by rtrox** [comment]
I'm not able to repro on my end, I have data for `sonarr_episode_quality_total`. Did you set `ENABLE_ADDITIONAL_METRICS`? That metric is gated behind that setting, since it requires a separate API call.

https://github.com/onedr0p/exportarr/blob/master/internal/collector/sonarr/series.go#L204

**Comment by Y0ngg4n** [comment]
@rtrox ah yeah that was it.

**Comment by Y0ngg4n** [comment]
@rtrox just have another problem too. Readarr wont even start:
I always get this:
`No help topic for 'readarr'`

**Comment by onedr0p** [comment]
What version of readarr are you using?

**Comment by rtrox** [comment]
Also, what version of exportarr? Right now readarr is only in master.

**Comment by Y0ngg4n** [comment]
@rtrox yeah was on an old version. there was an issue pulling the latest version in my configuration
