### ISSUE TITLE
WDYT? Refactoring to use `InvalidMetric` on errors, rather than `log.Fatal`

### ISSUE THREAD

**Issue by rtrox** [onedr0p/exportarr#105]
# Details

**Describe the solution you'd like:**

I'd love to discuss making the following two changes (I'm glad to do the work, but want @onedr0p's blessing first, since I know I'm suggesting a refactor which will result in a slight change in behavior):

1. Add a `<service>_scrape_duration_seconds` metric to capture some of the timing information we're currently logging to debug
3. Move from `log.Fatal` to `NewInvalidMetric` for registering errors in scrapes

**Anything else you would like to add:**

I was thinking about #49, and while I think the docker hang-ups are likely not related to `exportarr`, it might be being exacerbated by `log.Fatal` calls (which cause the process to `exit 1` and then be restarted by docker when errors are thrown). The `prometheus` docs recommend that when a collector hits an error collecting metrics from an endpoint. In the go prometheus library, we have [InvalidMetric](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#NewInvalidMetric) which can be passed back over the Collect channel to do this (there's a corresponding InvalidDesc which can be used for the Describe Channel).

I've been using this pattern on other exporters, and I've been playing around with it on a branch for exportarr. Any objection to me doing some refactoring to pass errors back to the collector so we can throw them with `InvalidMetric`?

**Additional Information:**

Docs for Metrics about Scrapes:
https://prometheus.io/docs/instrumenting/writing_exporters/#metrics-about-the-scrape-itself

Docs for Failed Scrapes:
https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes

**Comment by onedr0p** [comment]
@rtrox I believe this project could use a co-maintainer if you are interested!

And yes, I agree about the refactoring. I haven't been able to give this project the level of care I would like to be giving it (e.g. update some core libs like using koanf and zap)

**Comment by rtrox** [comment]
@onedr0p - Sure, would be glad to help maintain the project! I'll also be juggling against a day job as you are, but certainly two maintainers should help with coverage

**Comment by onedr0p** [comment]
Added. Feel free to create branches here for PRs instead of your own fork :)

**Comment by rtrox** [comment]
sounds good! I have a branch started here at the moment, but will start the next branch here.
