### ISSUE TITLE
Update flag `--enable-additional-metric` should be `--enable-additional-metrics`

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/exportarr#121]
# Details

**What steps did you take and what happened:**

Looks like I missed the change on this, but we should update the flag to be `--enable-additional-metrics` instead of `--enable-additional-metric`

**Comment by onedr0p** [comment]
@rtrox I will get to this in a few hours unless you have time now to update.

**Comment by rtrox** [comment]
gah, my bad. I can pull that fix into #120

**Comment by onedr0p** [comment]
That works!

**Comment by rtrox** [comment]
Sorry about that! I count too much on tab complete, and didn't notice the name change >.<
