### ISSUE TITLE
`sonarr_system_health_issues`  only exists in the dashboard2, not as an exported metric

### ISSUE THREAD

**Issue by bluefishforsale** [onedr0p/exportarr#134]
# Details

grafana/dashboard2.json has section for sonarr health

sonarr health in grafana/dashboard2.json depends on "expr": "sonarr_system_health_issues"

`sonarr_system_health_issues`  only exists in the dashboard, not as an exported metric
https://github.com/onedr0p/exportarr/search?q=sonarr_system_health_issues

Either the dashboard is out of date, or the metric exists in some branch other than master.

**Comment by onedr0p** [comment]
Also what you are looking for in code is here: https://github.com/onedr0p/exportarr/blob/3cd02da157cf691e5a176dac4f084e3d95376bff/internal/collector/shared/health.go#L23

**Comment by rtrox** [comment]
For health issues, though, we should probably be sending Zeroes when there's no issues though, I can create a PR for that.

https://github.com/onedr0p/exportarr/blob/3cd02da157cf691e5a176dac4f084e3d95376bff/internal/collector/shared/health.go#L56

**Comment by onedr0p** [comment]
> For sonarr, the episode_quality metric are hidden behind `ENABLE_ADDITIONAL_METRICS`/`--enable-additional-metrics`. In sonarr land, it requires additional API calls to get per-quality metrics, so there's a flag to enable it, where it's exported by default in radarr.

To iterate on this, I have roughly 500 series and 25k episodes and enabling the additional metrics causes the exportarr to take around 30 seconds to collect this data. Beware enabling it and adjust your intervals as such.
