### ISSUE TITLE
Unable to retrieve data into Grafana

### ISSUE THREAD

**Issue by Plinz** [onedr0p/exportarr#14]
Hi,

Thanks for the work on this exporter.
I have a issue when I try to use the dashboard Radarr V3 or Sonarr V3 in Grafana with Exportarr set up.
I can see the data on the url http://smetric:9707/metrics where smetric is the docker Exportarr configurated for my instance of Sonarr. I set the Data Source URL to http://smetric:9707/metrics but Grafana still return the HTML code of the homepage :

```
{
  "request": {
    "url": "api/datasources/proxy/3/api/v1/query?query=sonarr_history_total&time=1605645283",
    "method": "GET",
    "hideFromInspector": false
  },
  "response": "<h1>Radarr Exporter</h1><p><a href='/metrics'>metrics</a></p>"
}
```

The problems seems to be related to the homepage of Exportarr which is located on http://smetric:9707

Do you have a idea to resolve this issue ?
Thanks

**Comment by onedr0p** [comment]
It doesn't seem like you are using prometheus to collect the metrics?  Grafana should be using the prometheus datasource to query these metrics.

**Comment by CyberPoison** [comment]
I have the same issue, and i can confirm than i use Prometheus as monitoring option on grafana.

I'm on kubernetes, and i used your helm yaml file and still not able to query the data on grafana.

**Comment by onedr0p** [comment]
Sorry it's been awhile since i've had time to work on this project. Unfortunately I'm not sure what the issue is.

**Comment by onedr0p** [comment]
Grafana expects the metrics to exist in Prometheus first. 

Make sure your Prometheus instance is able to pull in metrics.
