### ISSUE TITLE
Lidarr - Songs Missing Total - no data

### ISSUE THREAD

**Issue by reefland** [onedr0p/exportarr#146]
# Details

**What steps did you take and what happened:**

Reviewing data within Prometheus, `lidarr_songs_missing_total` returns an empty set.

![image](https://user-images.githubusercontent.com/16230914/230926841-1d3bc0c3-94fc-4165-b8f5-3bf2f39a0b45.png)

No type or description shown.
![image](https://user-images.githubusercontent.com/16230914/230927476-f4c1b2af-78ae-435a-96bc-2b23616b3704.png)

**What did you expect to happen:**

Expect it to return an  integer value of number of songs missing. 

**Anything else you would like to add:**

This is already set for Lidarr:
`ENABLE_ADDITIONAL_METRICS: true`

**Comment by rtrox** [comment]
It looks like as of v1.2.0, this was renamed to `lidarr_albums_missing_total` -- it was reported in #82 that the actual metric coming back described albums rather than songs. Change made in #119.

**Comment by reefland** [comment]
That seems right.  any idea why is `lidarr_songs_missing_total` still shown? additional cleanup needed?
