### ISSUE TITLE
Build and publish exportarr binaries to Github releases

### ISSUE THREAD

**Issue by douginoz** [onedr0p/exportarr#15]
Sorry, I'm new to Prometheus and node_exporter.  I've downloaded your zip and also via the git clone, but nowhere in the resulting files is there any executable or make file.  
I'm not using docker, just ubuntu 20.04.
The README.md says that to run it from CLI:
```
### Run from the CLI

```cmd
./exportarr --help
./exportarr sonarr --help
./exportarr radarr --help
```

#### Sonarr

```cmd
./exportarr sonarr \
  --port 9707 \
  --url http://127.0.0.1:8989 \
  --api-key amlmndfb503rfqaa5ln5hj5qkmu3hy18 \
  --enable-episode-quality-metrics
```
But there's no "./exportarr" anywhere.

How do I use this with Prometheus?

**Comment by onedr0p** [comment]
Missed this.

I have not published binaries for `exportarr`, those steps are for if you compile it yourself with `go`.

**Comment by DobyTang** [comment]
I tried to download and compile, but it fails to build.

Clone repo
`git clone https://github.com/onedr0p/exportarr.git`

Install Go (Ubuntu 18.04)
` sudo apt  install golang-go`

Check version
`go version
go version go1.10.4 linux/amd64
`

Execute build instruction
`go build
can't load package: package .: no Go files in /home/docker/exportarr
`

very stuck at this point.

**Comment by onedr0p** [comment]
Your go version is very low, this is compiled against 1.16.

But you can try `go build -o exportarr ./cmd/exportarr/`

**Comment by onedr0p** [comment]
Binaries will be attached to the next release 🎉
