### ISSUE TITLE
api-key is required to not be empty

### ISSUE THREAD

**Issue by tylercranston** [onedr0p/exportarr#154]
# Details

**What steps did you take and what happened:**

- Upgraded to latest exportarr v1.3.1
- Error message shown in logs:
ApiKey:
 required: api-key is required to not be empty

**What did you expect to happen:**

exportarr reads ApiKey from /config/config.xml

The following values are defined as environment variables:

        env:
          - name: URL
            value: "http://localhost"
          - name: CONFIG
            value: "/config/config.xml"
          - name: PORT
            value: "9792"
          - name: ENABLE_ADDITIONAL_METRICS
            value: "true"
          - name: ENABLE_UNKNOWN_QUEUE_ITEMS
            value: "false"

The following is my Radarr /config/config.xml:

```
<Config>
  <LogLevel>info</LogLevel>
  <UrlBase />
  <Branch>develop</Branch>
  <ApiKey>XXXXXXXXXXXX</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <InstanceName>Radarr</InstanceName>
  <PostgresUser />
  <PostgresPassword />
  <PostgresPort>5432</PostgresPort>
  <PostgresHost />
  <PostgresMainDb />
  <PostgresLogDb />
  <Port>7878</Port>
  <BindAddress>*</BindAddress>
  <LaunchBrowser>False</LaunchBrowser>
  <EnableSsl>False</EnableSsl>
  <SslPort>6969</SslPort>
  <SslCertPath />
  <SslCertPassword />
  <UpdateMechanism>Docker</UpdateMechanism>
  <AnalyticsEnabled>False</AnalyticsEnabled>
</Config>
```

**Additional Information:**

**Comment by rtrox** [comment]
Hey @tylercranston, sorry for the delayed update here -- had some health issues in the family the last couple weeks that pulled me away. I'm looking at this today. A few releases ago, we swapped to using a validation library for validation, and some of the logic here changed, I imagine there's an order of operations issue here somewhere. I'll look at this today and get this updated.

**Comment by tylercranston** [comment]
@rtrox No problem, hope your family is doing better. Thanks for looking at this I appreciate it.

**Comment by rtrox** [comment]
PR for the fix is up -- thanks for finding this, @tylercranston.
