### ISSUE TITLE
Sabnzbd Dashboard - comments welcomed

### ISSUE THREAD

**Issue by reefland** [onedr0p/exportarr#155]
Working on a Sabnzbd dashboard panel.  Most of the metrics currently reset to zero after each container restart.  So lots of zero's here.

![image](https://user-images.githubusercontent.com/16230914/232791714-04b13391-90a3-44a3-95e2-a3fba6a8aba0.png)

Not sure which metrics are worth having on the dashboard.  This is my first draft.

Comments welcomed before I open a PR.

**Comment by rtrox** [comment]
This looks great! I think you and I came up with fairly similar answers:
![image](https://user-images.githubusercontent.com/5419724/234939210-512f784d-9264-43cb-921a-5a9dc5280db2.png)

My config is here if there's anything you think you'd like to pull in:
https://github.com/rtrox/prometheus-sabnzbd-exporter/blob/main/grafana-dashboards/dashboard.json

I'm happy with yours as is, if you want to open a PR. When you do, would you mind pulling this screenshot into the [grafana examples readme ](https://github.com/onedr0p/exportarr/blob/master/examples/grafana/README.md)? (It would be great if you could add a screenshot for the lidarr dashboard too)

**Comment by reefland** [comment]
ohhh... pretty.  I like that. Will work on combining.

**Comment by reefland** [comment]
Still a work in progress...
![image](https://user-images.githubusercontent.com/16230914/235169117-78b0e24b-cabe-448a-95f5-fed3f348442a.png)

Questions on your dashboard....
1. You have quota usage in 2 different locations on top row.  One in the middle seems right.  The one on the far right to me seems more like your article success rate so I called it that.
2. Your Free Disk Space, is actually space used.  So you are at nearly 80% disk space used not free.  Right?

**Comment by rtrox** [comment]
Yes, you're right! There was actually a bug prior which swapped used/free and I hadn't updated the dashboard. Good catch!

**Comment by techcubs** [comment]
Hi, how do we add sabnzbd metrics using Exportarr? or is it still a work in progress? i tried using sabnzbd command but it says:  Error: unknown command "sabnzbd" for "exportarr"

**Comment by rtrox** [comment]
Hey @techcubs - SabnzbD was added in `v1.3.0`, so you'll need to be using either that version or the latest (`v1.3.1`) for `sabnzbd` to be available as a command.

From there, something like this will work:
```
exportarr sabnzbd --api-key <your key> \
                                --url <your sab server> \
                                --port 8081 
```

If you're having trouble getting it going, you can open another github issue where you can give us more info to help debug.

**Comment by ragingpastry** [comment]
> Still a work in progress... ![image](https://user-images.githubusercontent.com/16230914/235172641-70c3b846-7fa0-4fb8-952d-5d34fca52072.png)
> 
> Questions on your dashboard....
> 
>     1. You have quota usage in 2 different locations on top row.  One in the middle seems right.  The one on the far right to me seems more like your article success rate so I called it that.
> 
>     2. Your Free Disk Space, is actually space used.  So you are at nearly 80% disk space used not free.  Right?

You got a link for your dashboard?

**Comment by reefland** [comment]
I'll be submitting a PR probably this week after some more testing.

**Comment by reefland** [comment]
Article success metrics keep breaking upstream... Not much I can do about that.  Stayed away from it for now. This dashboard seems reasonably clean. Open to ideas.  

![sabnzbd_dashboard](https://user-images.githubusercontent.com/16230914/236517660-accd75cd-ab3b-499d-a62f-bc4f6915e0c0.png)

**Comment by onedr0p** [comment]
Thanks for the PR, the dashboard looks amazing!
