### ISSUE TITLE
Issues created via template are not having their labels added

### ISSUE THREAD

**Issue by rtrox** [onedr0p/exportarr#159]
# Details

**What steps did you take and what happened:**

Created feature request issue, and no label was applied.

**What did you expect to happen:**

Based on issue template, a `kind:enhancement` label should have been added.

**Anything else you would like to add:**

Tried to look at this since it seemed like an easy fix. It may just be that the labels are named `enhancement` and `bug` rather than `kind:enhancement` and `kind:bug`. I tried to look at the docs to see if the labels should be created automatically, and I don't see that docs for markdown based templates still exist. It looks like the new way to do this is via issue forms:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

I'm not sure which is better, to try and convert to the forms, or just experiment with label names on the issue template to try and get labels working

**Additional Information:**

**Comment by onedr0p** [comment]
Good find, I'll get to this and hopefully make it a bit simpler.

**Comment by rtrox** [comment]
I'm silly -- the markdown stuff is still there. I tested it on a fork, it's just that the markdown references labels which don't exist (`kind:bug` vs `bug`).

I'll go ahead and get a quick pr to fix the labels up. It sounds like you're going to play with forms, so I'll leave that to you :-)

**Comment by onedr0p** [comment]
I'm torn between a form and a free field. Personally I like free form but that's because I try to be as detailed in reporting bugs to people haha. I think it's probably fine as is.

**Comment by rtrox** [comment]
Sounds good! I only brought up the form because I couldn't find docs for the markdown approach :-D turns out I skimmed the docs too quickly. I prefer free form too, we can always press for more info when they're not followed. I'll close this issue.
