### ISSUE TITLE
Docker contain exits

### ISSUE THREAD

**Issue by boostedgti916** [onedr0p/exportarr#167]
I have set this up using the docker compose example. When I try to go to the url  http://127.0.0.1:9707/metrics or  http://127.0.0.1:9708/metrics the contain will exit right away. I have updated the compose file with my IP and API key for sonarr and radarr. Any help?

**Comment by rtrox** [comment]
can you share the logs from the container?

**Comment by boostedgti916** [comment]
> can you share the logs from the container?

Just figured it out. I had to add /sonarr and /radrr to the end of my URL. Setting up the dashboard now. Thank you!

**Comment by rtrox** [comment]
Not much to go on --
