### ISSUE TITLE
Create a k8s manifest example which follows sidecar pattern

### ISSUE THREAD

**Issue by rtrox** [onedr0p/exportarr#182]
# Details

**Describe the solution you'd like:**

As title -- #180 is adding a k8s example which adds containers for all monitored *arrs in a single pod. We should add an alternate example which embeds exportarr as a sidecar in the *arr pod itself, consistent with the pattern being discussed in #133  for `app-template`.

**Anything else you would like to add:**

**Additional Information:**

**Comment by rtrox** [comment]
Added good first issue tag here, this feels pretty straightforward. This is also the pattern my cluster follows, I can likely create a PR in a bit if noone is interested in picking this up.

**Comment by onedr0p** [comment]
I think it might be a good idea to supply a helm chart and package it as an oci artifact people can use. I would like to defer that until the common library rewrite is completed though.

https://github.com/bjw-s/helm-charts/pull/148

As for the sidecar pattern that can be done as well but maybe with documentation?

**Comment by rtrox** [comment]
@onedr0p makes sense. I'll close this in favor of #133  then, that seems like the pattern we want to document. CC @reefland who was working on an `app-template` example

**Comment by onedr0p** [comment]
I'll open a new issue to track building a helm chart and packaging it in OCI and we can coalesce all these issues and PRs into one piece.
