### ISSUE TITLE
Release a Helm chart and package it with OCI

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/exportarr#183]
# Details

**Describe the solution you'd like:**

Build and release a Helm Chart for people to consume with Kubernetes. The helm chart would deploy a single exporter of choosing, and not support deploying multiple exporters within a single helm release.

**Comment by pchang388** [comment]
Hey first wanted to say thanks for creating this project, been using it recently and it's been helpful!

I was searching the issues here to see if a different `arr` related application was supported and stumbled on this. Not sure if this is exactly what you are looking for but I have a helm chart for exportarr with traditional `index.yaml` and OCI support that I use for my personal instances. Just wanted to share for anyone else and maybe save you some time

[exportarr chart](https://github.com/homeylab/helm-charts/tree/main/charts/exportarr)
