### ISSUE TITLE
Add Readarr integration

### ISSUE THREAD

**Issue by kinduff** [onedr0p/exportarr#21]
# Details

**Describe the solution you'd like:**

Integrate Readarr since its part of the "arr" apps but for reading.

**Anything else you would like to add:**

No API documentation but the API is very similar to Lidarr, see https://github.com/Readarr/Readarr/tree/develop/src/Readarr.Api.V1

**Additional Information:**

- https://readarr.com/

**Comment by kinduff** [comment]
Can work on this now if you're okay with the integration @onedr0p

**Comment by onedr0p** [comment]
Absolutely, I would just make sure we label this as "alpha" in the docs because Readarr doesn't have a "stable" or even "beta" release yet

**Comment by kinduff** [comment]
Sounds good!

**Comment by rtrox** [comment]
API docs exist here, now:
https://readarr.com/docs/api/

**Comment by onedr0p** [comment]
`ghcr.io/onedr0p/exportarr:master` has the latest bits for readarr, I would love for people to try it out and report back if there are any problems. If I don't hear anything I'll go ahead and make a release.
