### ISSUE TITLE
Latests version crashes on request

### ISSUE THREAD

**Issue by 100lv** [onedr0p/exportarr#230]
# Details

I'm using docker with tag for latest version. Since 1 week when I run container and on first attempt to request metrics containers crashes with:
 sonarr-exporter  | 2023-10-17T13:26:14.970Z     INFO    Starting exportarr      {"app_name": "exportarr", "version": "vmaster", "buildTime": "2023-10-08T18:15:27.347Z", "revision": "b8426af721e5ec7cdeae612686ef9c8083ffc85a"}
sonarr-exporter  | 2023-10-17T13:26:14.971Z     INFO    Starting HTTP Server    {"interface": "0.0.0.0", "port": 9707}
sonarr-exporter  | 2023-10-17T13:26:19.812Z     INFO    Sending HTTP request    {"url": "http://sonarr:8989/api/v3/series"}
sonarr-exporter  | 2023-10-17T13:26:19.812Z     INFO    Sending HTTP request    {"url": "http://sonarr:8989/api/v3/system/status"}
sonarr-exporter  | panic: assignment to entry in nil map
sonarr-exporter  |
sonarr-exporter  | goroutine 35 [running]:
sonarr-exporter  | net/url.Values.Add(...)
sonarr-exporter  |      /usr/local/go/src/net/url/url.go:902
sonarr-exporter  | github.com/onedr0p/exportarr/internal/arr/collector.(*queueCollector).Collect(0xc0000c1fc8, 0xc000293760?)
sonarr-exporter  |      /build/internal/arr/collector/queue.go:52 +0x225
sonarr-exporter  | github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
sonarr-exporter  |      /go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:455 +0x102
sonarr-exporter  | created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 29
sonarr-exporter  |      /go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:547 +0xbab

When I'm using v.1.5.5 - everything works OK.

**Comment by onedr0p** [comment]
Are you able to share the configuration you're using?

**Comment by 100lv** [comment]
API key is correct and removed before post.






  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.5.5
    container_name: sonarr-exporter
    command: ["sonarr"]
    environment:
      PORT: 9707
      URL: "http://sonarr:8989"
      APIKEY: "xxxxxxxxxxxxxx"
               
      ENABLE_ADDITIONAL_METRICS: "true"

    networks:
      - t2_proxy
    ports:
      - "9707:9707"
    restart: unless-stopped

**Comment by rdotts** [comment]
I'm getting this too.  Like @100lv, specifying v1.5.5 works.  I notice that while the repo says 1.5.5 is the latest, the docker repo has an image built about a week after that, and that's the image that the "latest" tag is pointing to.  It also has the tag "vmaster", which seems to be some sort of Windows-based vm storage thing (???).

Anyway, while I don't mean to presume, it seems like the "latest" tag shouldn't be pointing at it.  Hopefully this helps.

**Comment by onedr0p** [comment]
I'm guessing something broke between the release and commits into master... In any case it's best to pin your image to the latest release semver tag.

**Comment by rtrox** [comment]
I can look at this tonight, it looks like there's a codepath where the map isn't getting initialized, should be a quick fix.

In anycase, the `vmaster`/`latest` tag should be looked at as pre-release, you want the semver tag as onedr0p mentioned.

**Comment by RickyCook** [comment]
If it helps, according to my monitoring this seemed to start occurring a relatively long time ago (I update nightly and the first crash appeared at ~ 2023-10-09 06:52:00 UTC, so the commit/build would have been some time in the 24hr before that)

**Comment by rtrox** [comment]
Thanks Ricky, there's a PR up with the fix. Once that lands, it will get pushed to latest automatically.

**Comment by 100lv** [comment]
Thanks!
