### ISSUE TITLE
SABnzbd - runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by andrewtwelch** [onedr0p/exportarr#252]
# Details

**What steps did you take and what happened:**

Ran the exportarr container configured for SABnzbd (docker compose config below), and all requests return the following error:

`An error has occurred while serving metrics:

error collecting metric Desc{fqName: "sabnzbd_collector_error", help: "Error getting stats", constLabels: {target="<SABNZBD URL>"}, variableLabels: {}}: failed to get server stats: Failed to get server stats: Recovered from panic: runtime error: index out of range [-1]`

**What did you expect to happen:**

exportarr to present metrics from SABnzbd

**Anything else you would like to add:**

Currently running the container image tagged latest, and SABnzbd 4.2.1

**Additional Information:**

docker-compose.yml contents (relevant sections):
`  exportarr-sabnzbd:
    image: ghcr.io/onedr0p/exportarr:latest
    container_name: 'exportarr-sabnzbd'
    command: ['sabnzbd']
    restart: unless-stopped
    environment:
      PORT: 9709
      URL: '<SABNZBD URL>'
      APIKEY: '<SABNZBD API KEY>'
    ports:
      - '9709:9709'`

**Comment by andrewtwelch** [comment]
`An error has occurred while serving metrics:`
`error collecting metric Desc{fqName: "sabnzbd_collector_error", help: "Error getting stats", constLabels: {target=""}, variableLabels: {}}: failed to get server stats: Failed to get server stats: Recovered from panic: runtime error: index out of range [-1]`

`exportarr-sabnzbd:`
`  image: ghcr.io/onedr0p/exportarr:latest`
`  container_name: 'exportarr-sabnzbd'`
`  command: ['sabnzbd']`
`  restart: unless-stopped`
`  environment:`
`    PORT: 9709`
`    URL: '<SABNZBD URL>'`
`    APIKEY: '<SABNZBD API KEY>'`
`  ports:`
`    - '9709:9709'`

**Comment by rtrox** [comment]
Looks like the issue described in #246 - as far as I can tell from that PR, this happens when the statistic map coming back from Sabnzbd empty. AFAIK, this should only be true when a new sabnzbd instance is spun up, and no downloads have happened, in which case it should start returning stats once your first download starts. Does that match your situation?
