### ISSUE TITLE
Support tdarr

### ISSUE THREAD

**Issue by phyzical** [onedr0p/exportarr#254]
https://github.com/HaveAGitGat/Tdarr/issues/166

starting point looks to be `api/v2/cruddb`

Will look at doing this over the next couple of weeks

**Comment by onedr0p** [comment]
Personally I would like this project to only support open source projects. Tdarr is closed source software.

**Comment by pchang388** [comment]
@phyzical  

Offering these as an alternative:

https://github.com/homeylab/tdarr-exporter
https://github.com/homeylab/helm-charts/tree/main/charts/tdarr-exporter

Hope it helps

**Comment by phyzical** [comment]
no worries @onedr0p 👍 

thanks for the links @pchang388
