### ISSUE TITLE
API Key Regex is overly restrictive

### ISSUE THREAD

**Issue by ionfury** [onedr0p/exportarr#269]
# Details

I'm using [kubernetes-secret-generator](https://github.com/mittwald/kubernetes-secret-generator) to create and sync API keys for my *arr stack.  I'm using the `type: base64url` for these keys, which can include upper and lowercase letters.  Exportarr requires the API key provided to it conform to a 32 character hex string [here](https://github.com/onedr0p/exportarr/blob/933ed39eba6ecbadfec8d7a9f9f71a07c05d56cb/internal/arr/config/arr.go#L43).  Exportarr will not accept the API keys I'm using in my cluster for my *arr applications because they do not conform to this regex.

**What did you expect to happen:**

Exportarr to either:
- Conform to the api key requirements of the *arr stack applications ([lidarr example](https://github.com/Lidarr/Lidarr/blob/57926a61d27e0fbb02f7e1a3f90bfba71f3bd294/src/NzbDrone.Core/HealthCheck/Checks/ApiKeyValidationCheck.cs#L27))
- Not restrict this input.

**Anything else you would like to add:**

I don't understand the purpose the input validation is serving here.  I believe I can regenerate my keys using the [`hex`](https://github.com/ionfury/homelab/blob/ab092bf61894f647cad10fd0788ba83ee0b780b4/manifests/apps/lidarr/kustomization.yaml#L10) type, but I'd like to understand why this restriction exists before I either regenerate all my keys or open PR here.

**Additional Information:**

[IaC api key generation](https://github.com/ionfury/homelab/blob/ab092bf61894f647cad10fd0788ba83ee0b780b4/manifests/apps/lidarr/kustomization.yaml#L10)

**Comment by onedr0p** [comment]
I honestly thought that the arrs only every generated and accepted `a-z0-9{32}`, while the former may be true the latter doesn't look to be.

**Comment by ionfury** [comment]
That would do nicely 💯

**Comment by onedr0p** [comment]
Container image for https://github.com/onedr0p/exportarr/releases/tag/v1.6.2 is building now, enjoy!

**Comment by ionfury** [comment]
Works great, thanks for the quick turnaround!
