### ISSUE TITLE
Cannot add to Grafana

### ISSUE THREAD

**Issue by bezibaerchen** [onedr0p/exportarr#271]
Containers up and running and I can access in Browser.

If I add hostname:port to Grafana as a prometheus source I am getting:

"ReadObject: expect { or , or } or n, but found <, error found in #1 byte of ...|<h1>Exporta|..., bigger context ...|<h1>Exportarr</h1><p><a href='/metrics'>metrics</a>|... - There was an error returned querying the Prometheus API."

Any hint how to add the data source? And is there an example dashboard?

**Comment by onedr0p** [comment]
Grafana must be pointed to use the Prometheus source, you cannot point the dashboard included here directly at the exportarr metrics endpoint.

Related: https://github.com/onedr0p/exportarr/issues/14

**Comment by bezibaerchen** [comment]
I am not trying to point a dashboard to the metrics but the Prometheus source and am getting error above.
I can't even find the dashboard you mentioned, hence I was asking for it.

**Comment by rtrox** [comment]
Example Dashboards can be found in the examples directory:

https://github.com/onedr0p/exportarr/tree/master/examples/grafana

----

> [metrics](https://github.com/metrics)|... - There was an error returned querying the Prometheus API."

> Any hint how to add the data source? And is there an example dashboard?

This error is not coming from exportarr -- exportarr does not talk to prometheus directly, it exposes an http endpoint which prometheus should be scraping.  You'll need to set up a scrape config in your prometheus instance to read from exportarr.
