### ISSUE TITLE
Github and Discord link not working

### ISSUE THREAD

**Issue by Panda260** [onedr0p/exportarr#278]
Github and Discord link not working

**Comment by onedr0p** [comment]
What Github and Discord link are you referring to?

**Comment by Panda260** [comment]
![image](https://github.com/onedr0p/exportarr/assets/52088459/5186b73c-59d6-430a-be44-fe5d9d21ef3f)

**Comment by onedr0p** [comment]
Fix in https://github.com/onedr0p/exportarr/commit/1db0b074fc6d671c2074ae4717a7861cbaf14f23

thanks!
