### ISSUE TITLE
how to get the data into grafana

### ISSUE THREAD

**Issue by Panda260** [onedr0p/exportarr#279]
Hey so i have everything installed everything is working the installation of exportarr was successfully and i now have the websides with the metrics but how can i geht the data from that side into grafana?

**Comment by onedr0p** [comment]
You need to have prometheus deployed which scrapes exportarr, then Grafana needs to use prometheus as a datasource.

See https://github.com/onedr0p/exportarr/issues/271 and https://github.com/onedr0p/exportarr/issues/14
