### ISSUE TITLE
Malicious JS ?

### ISSUE THREAD

**Issue by fistyeshyx** [onedr0p/exportarr#283]
/assets/index-0e4afa5f.js

malicious payload?

a redirector ?

File Type: JS

Submitted Date: 2024/04/01 22:12:46
Last Analyzed: 2024/04/01 22:12:57
URL: http://xxx.xxx.xxx.xxx/assets/index-0e4afa5f.js
File Name: index-0e4afa5f.js
SHA256: 6dfebeb4b3179991c5b1acb230a02dc7c5b9c782241dd2abf4898582848b27ec
SHA1: a67e708ab1b7624a3be6d425e9995ee2f367a8bc

**Comment by onedr0p** [comment]
This project has no javascript at all.
