### ISSUE TITLE
Radarr - Logs reporting startup on Sonarr port 9708

### ISSUE THREAD

**Issue by DobyTang** [onedr0p/exportarr#29]
# Details

**What steps did you take and what happened:**

Followed the Readme to install Docker exportarr_radarr instance
```
sudo docker run --name exportarr_radarr \
  -e port=9708 \
  -e URL="http://192.168.nn.nn:7878" \
  -e APIKEY="0dxxxxxxxxxd7" \
  --restart unless-stopped \
  -p 9708:9708 \
  -d ghcr.io/onedr0p/exportarr:latest exportarr radarr
```

Viewed the logs with 
`**sudo docker logs --follow exportarr_radarr**
`
output was 
`**time="2021-03-21T21:32:17Z" level=info msg="Listening on 0.0.0.0:9707"**
`
**What did you expect to happen:**

Expected 
`time="2021-03-21T21:32:17Z" level=info msg="Listening on 0.0.0.0:**9708**"
`

**Anything else you would like to add:**

Issuing a curl command returned 
`curl -X GET http://127.0.0.1:9708/metrics
`

result was 
`curl: (56) Recv failure: Connection reset by peer
`

**Additional Information:**

So it appears the radarr metrics were started correctly.

**Comment by onedr0p** [comment]
`-e PORT` not `-e port`
