### ISSUE TITLE
Series to be downloaded and today 

### ISSUE THREAD

**Issue by 100lv** [onedr0p/exportarr#290]
It will be great if you can add to Sonarr option to see aired today episodes and are they downloaded or no.

**Comment by codefaux** [comment]
While it doesn't seem realistic to add this to the exportarr series, it is easy to add JSON data directly to Grafana without an exporter and prometheus, and build it into a dashboard.

I've decided to fiddle with a direct JSON dashboard for Servarr products, starting with this feature for Sonarr. Bare minimum information is present to get it running. Progress will probably be slow.

https://github.com/codefaux/grafana-dashboard-sonarr

**Comment by rtrox** [comment]
Yea, +1 -- prometheus in general is meant for metrics, rather than text output. a

More info on a JSON datasource here:
https://grafana.com/grafana/plugins/simpod-json-datasource/
