### ISSUE TITLE
Api key file not working

### ISSUE THREAD

**Issue by jordycoding** [onedr0p/exportarr#291]
# Details

I am running exportarr under nixos, but API_KEY_FILE doesn't seem to work. It gives the error ```regex: api-key must be a 20-32 character alphanumeric string```. It is provided in the systemd service using loadcredential.

**Anything else you would like to add:**
This is the nix service declaration, I see nothing wrong with it, the environment variable seems to be correclty set at the top of the file
[NixOS service declaration](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/monitoring/prometheus/exporters/exportarr.nix#L47)

**Comment by onedr0p** [comment]
You might want to open an issue over in nixpkgs or talk to the maintainers there? I know nix does things differently and I am not the best person for asking for support with nix.

**Comment by onedr0p** [comment]
With that said, it looks like you need a api-key file on disk with the contents being the api key.

**Comment by jordycoding** [comment]
Thanks for the quick reply, I'll do that
