### ISSUE TITLE
All-apps-at-once exporting

### ISSUE THREAD

**Issue by nfx** [onedr0p/exportarr#295]
Nice tool!

> Note: This exporter will not gather metrics from all apps at once. You will need an exportarr instance for each app. 

Is there any reason (other than the lack of time), that all services are no exportable at once? e.g. prowlarr has API keys and hosts to all other things in the stack, so theoretically it could be used as an entrypoint... happy to do some digging.

**Comment by rtrox** [comment]
@nfx - Good Question! We generally try to follow the prometheus best practices for writing exporters, and the deployment pattern that prometheus pushes is "one exporter for one application":

> Each exporter should monitor exactly one instance application, preferably sitting right beside it on the same machine. That means for every HAProxy you run, you run a haproxy_exporter process. For every machine with a Mesos worker, you run the [Mesos exporter](https://github.com/mesosphere/mesos_exporter) on it, and another one for the master, if a machine has both.
https://prometheus.io/docs/instrumenting/writing_exporters/#deployment

So generally we recommend running it as a sidecar inside the same pod/compose file as the app it's monitoring.
