### ISSUE TITLE
Sonarr configuration isn't rendering metrics

### ISSUE THREAD

**Issue by DobyTang** [onedr0p/exportarr#30]
# Details

**What steps did you take and what happened:**
Installed Docker Sonarr
`docker ps
 linuxserver/sonarr                 "/init"                  3 years ago         Up 9 hours          0.0.0.0:8989->8989/tcp   sonarr`

Installed exportarr_sonarr (as per Readme)
`ghcr.io/onedr0p/exportarr:master   "/sbin/tini -- expor…"   8 seconds ago       Up 7 seconds        0.0.0.0:9707->9707/tcp   exportarr_sonarr`

Tried both configurations 
1. with API key specified
```
sudo docker run --name exportarr_sonarr \
  -e port=9707 \
  -e URL="http://192.168.nn.nn:8989" \
  -e APIKEY="53xxxxxxxxxxxxxxxxxxx2b" \
  -e LOG_LEVEL="DEBUG" \
  --restart unless-stopped \
  -p 9707:9707 \
  -d ghcr.io/onedr0p/exportarr:master exportarr sonarr
```

2. with config.xml referenced
```
sudo docker run --name exportarr_sonarr   -e port=9707   -e URL="http://192.168.nn.nn:8989" \
 -e CONFIG=/home/docker/sonarr/config/config.xml \
 -e LOG_LEVEL="DEBUG"   --restart unless-stopped   -p 9707:9707   \
-d ghcr.io/onedr0p/exportarr:master exportarr sonarr
```

All start okay, 
`time="2021-03-21T21:44:38Z" level=info msg="Listening on 0.0.0.0:9707"
`
the home page would render, 
```
$> curl -X GET localhost:9707
<h1>Exportarr</h1><p><a href='/metrics'>metrics</a></p>

time="2021-03-21T21:46:37Z" level=debug msg="172.17.0.1:53210 GET /\n"

```
but the metrics page returns 404 in the logs

```
curl -X GET localhost:9707/metrics
curl: (52) Empty reply from server
```
but the logs report
```
time="2021-03-21T21:47:33Z" level=debug msg="172.17.0.1:53232 GET /metrics\n"
time="2021-03-21T21:47:33Z" level=info msg="Sending HTTP request to http://192.168.nn.nn:8989/api/v3/history"
time="2021-03-21T21:47:33Z" level=info msg="Sending HTTP request to http://192.168.nn.nn:8989/api/v3/rootfolder"
time="2021-03-21T21:47:33Z" level=info msg="Sending HTTP request to http://192.168.nn.nn:8989/api/v3/queue?page=1"
time="2021-03-21T21:47:33Z" level=info msg="Sending HTTP request to http://192.168.nn.nn:8989/api/v3/health"
time="2021-03-21T21:47:33Z" level=info msg="Sending HTTP request to http://192.168.nn.nn:8989/api/v3/system/status"
time="2021-03-21T21:47:33Z" level=info msg="Sending HTTP request to http://192.168.nn.nn:8989/api/v3/series"
time="2021-03-21T21:47:33Z" level=fatal msg="An error has occurred during retrieving statistics HTTP statuscode 404"
```

**What did you expect to happen:**

I expected the metrics page to render in the ui or return a valid response in the curl command

**Anything else you would like to add:**

The Sonarr instance is running for.3 years, no issues with it and the exportarr renders the home page so I suspect there is something between the connection of the two docker containers but I cannot see what it is

**Additional Information:**

**Comment by onedr0p** [comment]
using the `config.xml` is a bit advanced config, I would not suggest using it.

Also, are you using v3 of Sonarr and  Radarr?
