### ISSUE TITLE
Handle Multiple API Keys

### ISSUE THREAD

**Issue by JamesTeague** [onedr0p/exportarr#31]
# Details

**Describe the solution you'd like:**

I've got two instances of Radarr and one of Sonarr running in a Kubernetes cluster. It would be nice to be able to only have to run 1 deployment to monitor these. Right now I have to run 3.

**Anything else you would like to add:**

**Additional Information:**

I understand this would cause some issues with existing dashboards but I feel like that is out of this projects concern.

**Comment by onedr0p** [comment]
For now this is meant to be one exportarr instance per Radarr, Sonarr or Lidarr instance. But I am open to PRs :)

**Comment by JamesTeague** [comment]
Noted, I already thought about going that route but I thought I would get it on the radar.

**Comment by onedr0p** [comment]
I am going to close this issue because just like how we have to deploy separate radarr/sonarr instances they same is true for this app. Adding multi instance support is not easy and would require a lot of refactoring.
