### ISSUE TITLE
An error has occurred while serving metrics

### ISSUE THREAD

**Issue by tsull360** [onedr0p/exportarr#316]
# Details

**What steps did you take and what happened:**

Have compiled app into Windows binary. Running with the following command line; .\exportarr.exe radarr --port 9708 --url radarr.fabrikam.com --api-key 1234567890

Launched browser on my machine using the example format: http://[127.0.0.1:9708/metrics](http://127.0.0.1:9708/metrics)

Received the following output:

An error has occurred while serving metrics:

5 error(s) occurred:
* error collecting metric Desc{fqName: "radarr_queue_collector_error", help: "Error while collecting metrics", constLabels: {url="radarr.fabrikam.com"}, variableLabels: {}}: Failed to execute HTTP Request(radarr.fabrikam.com/api/v3/queue?page=1): Get "radarr.fabrikam.com/api/v3/queue?page=1": Error sending HTTP Request: unsupported protocol scheme ""
* error collecting metric Desc{fqName: "radarr_health_collector_error", help: "Error while collecting metrics", constLabels: {url="radarr.fabrikam.com"}, variableLabels: {}}: Failed to execute HTTP Request(radarr.fabrikam.com/api/v3/health): Get "radarr.fabrikam.com/api/v3/health": Error sending HTTP Request: unsupported protocol scheme ""
* error collecting metric Desc{fqName: "radarr_rootfolder_collector_error", help: "Error while collecting metrics", constLabels: {url="radarr.fabrikam.com"}, variableLabels: {}}: Failed to execute HTTP Request(radarr.fabrikam.com/api/v3/rootfolder): Get "radarr.fabrikam.com/api/v3/rootfolder": Error sending HTTP Request: unsupported protocol scheme ""
* error collecting metric Desc{fqName: "radarr_collector_error", help: "Error while collecting metrics", constLabels: {url="radarr.fabrikam.com"}, variableLabels: {}}: Failed to execute HTTP Request(radarr.fabrikam.com/api/v3/movie?excludeLocalCovers=true): Get "radarr.fabrikam.com/api/v3/movie?excludeLocalCovers=true": Error sending HTTP Request: unsupported protocol scheme ""
* error collecting metric Desc{fqName: "radarr_history_collector_error", help: "Error while collecting metrics", constLabels: {url="radarr.fabrikam.com"}, variableLabels: {}}: Failed to execute HTTP Request(radarr.fabrikam.com/api/v3/history): Get "radarr.fabrikam.com/api/v3/history": Error sending HTTP Request: unsupported protocol scheme ""

**What did you expect to happen:**

Expected to see page of metrics as output from radarr

**Anything else you would like to add:**

**Additional Information:**

**Comment by onedr0p** [comment]
Maybe sure you include the http uri scheme in the url argument.

**Comment by tsull360** [comment]
Thank you, that fixed it quite easily.
