### ISSUE TITLE
Add prowlarr integration

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/exportarr#35]
# Details

**Describe the solution you'd like:**

Prowlarr is slowly becoming the jackett and nzbhydra2 replacement but it's still in alpha.

**Comment by onedr0p** [comment]
Initial work was done in https://github.com/onedr0p/exportarr/pull/84 but it still needs some work done. See this comment on how it can be improved.

https://github.com/onedr0p/exportarr/pull/84#issuecomment-1213274598

**Comment by Y0ngg4n** [comment]
Would be nice to see what indexer performs the best by grabs

**Comment by rtrox** [comment]
It looks like #84 only added existing shared collectors (History, SystemStatus, and SystemHealth). If no one else picks this up, I might be able to take a look at this soon, it would be nice to have full prowlarr support

**Comment by onedr0p** [comment]
That would be awesome, I have been really busy lately and this project has gotten away from me but I always have time to review PRs.

**Comment by onedr0p** [comment]
`ghcr.io/onedr0p/exportarr:master` has the latest bits for prowlarr, I would love for people to try it out and report back if there are any problems. If I don't hear anything I'll go ahead and make a release.

**Comment by rtrox** [comment]
Example Dashboard for Prowlarr:
![image](https://user-images.githubusercontent.com/5419724/223573314-325650cd-c369-457c-ad9a-492132a5a545.png)

**Comment by Y0ngg4n** [comment]
@rtrox could you share the json?

**Comment by rtrox** [comment]
yep, let me pull out the prowlarr bits (this is part of a broader dashboard that includes sonarr, radarr, readarr, and prowlarr). I was planning on making a PR to include it in the /examples dir.

**Comment by rtrox** [comment]
Just created a PR to pull in my integrated dashboard ⬆️ . Here's the image of the full dashboard. Note that I don't use lidarr, so it isn't covered here.

![dashboard-2](https://user-images.githubusercontent.com/5419724/224109854-8176990b-0e77-4d51-87ce-5f73c8415134.png)

**Comment by rtrox** [comment]
Oh, one other note -- the "Network" graphs here assume these services are running in kubernetes. If running in docker, this will need to be adjusted (or deleted).

**Comment by Y0ngg4n** [comment]
@rtrox thank you :)

**Comment by Y0ngg4n** [comment]
@rtrox maybe it would be nice to add a day count to prowlarr backfill, like in the prowlarr stats itself. 
So you can say only the last 30 days or something, so you can minimize the risk to timeout. Because my prowlarr database is so full i always get a timeout.

**Comment by rtrox** [comment]
@Y0ngg4n can you create a feature request issue for this please? Probably need to discuss with one drop what such a cli flag would look like

**Comment by rtrox** [comment]
In the meantime, you can disable backfill or increase your scrape timeout, assuming exporter is timing out before prowler

**Comment by rtrox** [comment]
Both exporter code & dashboard has been merged for prowlarr, so I'm going to go ahead and close this pending a release.

If there's issues with prowlarr from here, let's open them as individual issues.
