### ISSUE TITLE
Add a Prowlarr integration

### ISSUE THREAD

**Issue by Aghassi** [onedr0p/exportarr#41]
# Details

Prowlarr aggregates metrics on the clients it uses and can report hit rates etc. It would be nice to be able to pipe these into prometheus and query with Grafana.

**Anything else you would like to add:**

For reference https://prowlarr.com

**Additional Information:**

**Comment by onedr0p** [comment]
Duplicate: https://github.com/onedr0p/exportarr/issues/35

Closing

**Comment by Aghassi** [comment]
Ah totally missed it, thank you!
