### ISSUE TITLE
Sonarr additionla info

### ISSUE THREAD

**Issue by 100lv** [onedr0p/exportarr#43]
It will be great if you can grab also few additional details into the sonarr/ radarr grabber like - missing episodes / movies, downloaded today / last week ; downloading and etc. In this case I can (and beleave that this is valid not only for me) retire varken, as it's not support and brings a lot of issues (Radarr is not working with V3 of the API, using InfluxDB 1.8 and etc.).

**Comment by onedr0p** [comment]
Prometheus metrics work a bi differently than influx. You should be able to use promql to aggregate any data you want.
