### ISSUE TITLE
docker-compose examples are out of date

### ISSUE THREAD

**Issue by philosowaffle** [onedr0p/exportarr#45]
# Details

**What steps did you take and what happened:**

Attempted to setup lidarr exporter using the docker-compose example.

**What did you expect to happen:**

Container should start and stay running. Metrics should be available for scraping.  Instead the container exited immediately with the following:

```
lidarr_prom_exporter    | No help topic for 'exportarr'
lidarr_prom_exporter exited with code 3
```

**Anything else you would like to add:**

I believe the following change is needed.

```diff
- command: ["exportarr", "lidarr"]
+ command: ["lidarr"]
```

I'm guessing this change may be valid for the other *arr setups as well.

Lidarr exporter starts and runs as expected after above change.

**Comment by philosowaffle** [comment]
Gotcha. No I'm on `master` tag. 

I had some confusion because I seem to have been using the 2 year old images on Docker Hub, not realizing that the new stuff was only on GCR. So I'm in the process of updating all my exportarr images.  I was using the `master` tag because that (a veeerrryyy long time ago apparently) was the only sort of "latest" available on Docker Hub.

**Comment by onedr0p** [comment]
I'll be sure to update the docs and examples on a new release.
