### ISSUE TITLE
Add Lidarr integration

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/exportarr#5]
I currently don't run Lidarr, but plan to.

**Comment by kinduff** [comment]
Would love to give it try

**Comment by onedr0p** [comment]
I'm open to PRs :)

**Comment by kinduff** [comment]
@onedr0p Getting a PR ready, first time using Go. The API is v1 for Lidarr, which kinda sucks because v3 is way better to fetch the data we are grabbing from Sonarr for example. I'm adding a few flags to make them optional and adding a disclaimer that it might be slow.

**Comment by onedr0p** [comment]
@kinduff awesome and to be honest I would only make it work with the latest API versions of the apps for less complexity. People using this exportarr are probably update to date anyways.

**Comment by kinduff** [comment]
@onedr0p That's the thing, Lidarr is still in development and they are not up to date with Radarr & Sonarr, so the v3 API is not available yet. Which is sad, but we are still able to fetch some nice data.

**Comment by onedr0p** [comment]
> @onedr0p That's the thing, Lidarr is still in development and they are not up to date with Radarr & Sonarr, so the v3 API is not available yet. Which is sad, but we are still able to fetch some nice data.

I _think_ they started at v1 instead of making it v3. So v1 is v3 for Lidarr.
