### ISSUE TITLE
sonarr_episode_quality_total - Missing from metrics

### ISSUE THREAD

**Issue by samcro1967** [onedr0p/exportarr#50]
# Details

**What steps did you take and what happened:**
Installed per the directions and scraped data.  sonarr_episode_quality_total is not displayed at 127.0.0.1:9707/metrics.  I do see radarr_episode_quality_total at 127.0.0.1:9708/metrics.  I see code for it in series.go.  Not sure why it is not being exported the metrics page.

**What did you expect to happen:**
Expected sonarr_episode_quality_total to be displayed at 127.0.0.1:9707/metrics.

**Anything else you would like to add:**
Running the latest docker image and Sonarr version 3.0.6.1471.

**Additional Information:**

**Comment by onedr0p** [comment]
Did you enable this config setting? 

https://github.com/onedr0p/exportarr/blob/master/internal/collector/sonarr/series.go#L136-L146

**Comment by samcro1967** [comment]
Ah.  Did not realize that was specific to Sonarr.  Did not add it since it was working with Radarr.  Thanks!

**Comment by techcubs** [comment]
Hi, I am also not seeing the qualities. here is what my docker-compose looks like.

  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:master
    command: ["sonarr"]
    restart: always
    environment:
      PORT: 9707
      URL: "https://sonarr.xxxxxxxx.xxxxxxx"
      APIKEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    ports:
      - "9707:9707"

prometheus.yml:

  - job_name: sonarr-exportarr
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
    - targets:
      - x.x.x.x:9707
    
 If I add ENABLE_ADDITIONAL_METRICS: true under sonarr-exporter environments, I get this error in prometheus: Get "http://192.168.1.79:9707/metrics": EOF

**Comment by onedr0p** [comment]
I would not use `:master` unless you need URL base support, please use a semantic tagged version, like `:v1.0.0`

**Comment by techcubs** [comment]
Thanks, Changing to v1.0.0 worked. :)
