### ISSUE TITLE
UrlBase Usage Issue

### ISSUE THREAD

**Issue by Hamxter** [onedr0p/exportarr#56]
# Details

Including a UrlBase value is causing and issue with the URL generation missing a "/". (Tested with sonarr and radarr)

**What steps did you take and what happened:**

1. Include a URL base.

![image](https://user-images.githubusercontent.com/21071130/160728252-3f2ec017-65db-464f-b9fe-feda50394e26.png)

2. The "/" is stripped when being saved to config.xml
`<Config>
  <LogLevel>info</LogLevel>
  <UpdateMechanism>Docker</UpdateMechanism>
  <BindAddress>*</BindAddress>
  <EnableSsl>False</EnableSsl>
  <SslCertPath></SslCertPath>
  <Port>7878</Port>
  <UrlBase>radarr</UrlBase>
  <ApiKey>...</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <SslPort>9898</SslPort>
  <LaunchBrowser>True</LaunchBrowser>
  <Branch>master</Branch>
  <SslCertPassword></SslCertPassword>
</Config>`

3. The program crashes due to invalid url
` |   | 2022-03-30 10:07:54 | panic: runtime error: invalid memory address or nil pointer dereference
  |   | 2022-03-30 10:07:54 | time="2022-03-30T00:07:54Z" level=info msg="Sending HTTP request to http://localhost:7878radarr/api/v3/movie"
  |   | 2022-03-30 10:07:54 | time="2022-03-30T00:07:54Z" level=info msg="Sending HTTP request to http://localhost:7878radarr/api/v3/health"
  |   | 2022-03-30 10:07:44 | time="2022-03-30T00:07:44Z" level=info msg="Listening on 0.0.0.0:9793"
  |   | 2022-03-30 10:07:44 | time="2022-03-30T00:07:44Z" level=info msg="Getting Config from /config/config.xml"
  |   | 2022-03-30 10:05:04 | /go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:538 +0xb4d
  |   | 2022-03-30 10:05:04 | created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
  |   | 2022-03-30 10:05:04 | /go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:446 +0x102
  |   | 2022-03-30 10:05:04 | github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
  |   | 2022-03-30 10:05:04 | /build/internal/collector/radarr/movie.go:93 +0x157
  |   | 2022-03-30 10:05:04 | github.com/onedr0p/exportarr/internal/collector/radarr.(*radarrCollector).Collect(0xc0000c4d20, 0xc000045f60)
  |   | 2022-03-30 10:05:04 | /build/internal/client/client.go:76 +0x6ed
  |   | 2022-03-30 10:05:04 | github.com/onedr0p/exportarr/internal/client.(*Client).DoRequest(0xc0001f0440, {0x91039d, 0x5}, {0x85aea0, 0xc0000acf90})
  |   | 2022-03-30 10:05:04 | goroutine 29 [running]:`

**What did you expect to happen:**

It's unclear to me why this issue hasn't come up for anyone else. I'm assuming the UrlBase value is being saved with a "/" for others.

At some point before or at this line of code, a "/" should be checked for and added if necessary.
https://github.com/onedr0p/exportarr/blob/a582d45d345f93378a22f828d3bb2869f0582d9f/internal/client/client.go#L47-L57

This will fix the URL to be http://localhost:7878/radarr/api/v3/health instead of http://localhost:7878radarr/api/v3/health

**Comment by onedr0p** [comment]
I'm guessing a lot of people that use this do not use a url base with sonarr or radarr but good find. I thought the urlbase was saved as `/radarr` in the `config.xml`

I'll need to think of a better way of handling this.

**Comment by HamishLaird** [comment]
You could always mimic the code that sonarr/radarr is using.

https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Configuration/ConfigFileProvider.cs#L187-L200

Mind you they have removed the toLowerCase for v4

**Comment by onedr0p** [comment]
That's another thing, I have to update these api calls to use the latest api versions someday 😅

For now I'll just create a function in the utils package that will handle the urlbase logic and use it.

**Comment by Hamxter** [comment]
Thank you. I appreciate the quick replies!!

**Comment by onedr0p** [comment]
I'll try to have something tomorrow you can test.

**Comment by onedr0p** [comment]
@Hamxter can you please try out the image `ghcr.io/onedr0p/exportarr:master` and let me know if that solves the issue?

Then image will be pushed when this succeeds https://github.com/onedr0p/exportarr/runs/5753721191?check_suite_focus=true

**Comment by Hamxter** [comment]
@onedr0p Just tested. Works perfectly
