### ISSUE TITLE
Refactor: Switch to koanf & cobra for config & CLI library

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/exportarr#58]
# Details

**Describe the solution you'd like:**

https://github.com/knadh/koanf

**Comment by onedr0p** [comment]
I discovered koanf from @james-d-elliott who maintains Authelia and it appears they use Cobra (which has a dep on pflag). So I'm fine with either Cobra or just pflag but Cobra might give us more options to play with overtop pflag

https://github.com/search?q=repo%3Aauthelia%2Fauthelia%20cobra&type=code

**Comment by rtrox** [comment]
Sounds good, makes sense to me! Just didn't want to look at replacing `urfave/cli` without chatting with you.
