### ISSUE TITLE
Provide default port

### ISSUE THREAD

**Issue by rubasace** [onedr0p/exportarr#7]
Any reason why you don't provide a default port? I'd be happy to stick to whatever you choose but I don't like having to write it twice on the k8s manifest, one for the envar and one for the `ports` section. What do you think?

**Comment by onedr0p** [comment]
I left it required without a default for UX reasons. I'd rather have a person see that the port is required than a port is already in use error when trying to run multiple (sonarr, radarr, and future) exporters, especially when running from the command line. Not to say this won't change, I am still thinking of ways to improve the exporter to work from a CLI or container perspective.

**Comment by rubasace** [comment]
But that's the same behaviour we already have with Sonarr/Radarr themselves. Though it's true not everybody runs multiple instances.

I think anyone going to use a Prometheus exporter will be running the stack in Docker, via compose, swarm, k8s or something, but I'd be surprised if anyone using this is running in from CLI.

Anyway, if that's your concern, why not just setting the ENV on the Dockerfile? like that, you'll provide default port for the container, which should not cause the issue unless running on host network, and CLI will still require a specific port for UX reasons.

**Comment by onedr0p** [comment]
I like that idea. I added default `PORT` in the Dockefile, set to `9707`, I also added tini, so the `ENTRYPOINT` has changed.

**Comment by rubasace** [comment]
Minor detail, but why using tini at all instead of using `ENTRYPOINT` in `EXEC` form? 
https://goinbigdata.com/docker-run-vs-cmd-vs-entrypoint/

The main benefit is that the container won't have an extra process for the shell

**Comment by onedr0p** [comment]
I use `tini` out of habbit, basically it doesn't do any harm and adds signal handling, and cleans up zombie processes. See this wonderful post by the author that can explain it better than me.

https://github.com/krallin/tini/issues/8#issuecomment-146135930

I have update the Dockerfile to add that line is above `ENTRYPOINT`

**Comment by rubasace** [comment]
Very interesting this tini thing, never heard of it before. Definitely will investigate it's usage at work for our JVM applications.

**Comment by onedr0p** [comment]
Funny you mention that, we have some JVM apps at work and I pretty much copied the way Jenkins does their containers.

https://github.com/jenkinsci/docker

**Comment by rubasace** [comment]
What stack are you using? Spring Boot by any chance? Are there any improvements you've observed like grateful shutdown or something like that?

**Comment by onedr0p** [comment]
We're using spring, but I don't have any information other than the app team saying it works fine, haha.
