### ISSUE TITLE
Can't add Metrics to Grafana as a Data Source

### ISSUE THREAD

**Issue by SnowJuli** [onedr0p/exportarr#72]
# Details

**What steps did you take and what happened:**

1. Selected Prometheus as a Data Source
2. Filled out my URL (http://pie.home:9707/metrics) directing to the Sonarr Exportarr Container
3. Pressed Save&Test
4. Error appeared:
```
Error reading Prometheus: bad_response: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<h1>Exporta|..., bigger context ...|<h1>Exportarr</h1><p><a href='/metrics'>metrics</a>|...)
```

**What did you expect to happen:**
That it can be added as a Data Source

**Anything else you would like to add:**
/

**Additional Information:**
Using Docker Containers

**Comment by onedr0p** [comment]
The metrics need to be scraped by Prometheus, so prometheus should be the data source in Grafana.
