### ISSUE TITLE
Automatically retrieve API key

### ISSUE THREAD

**Issue by ProfessorSalty** [onedr0p/exportarr#8]
Hi there! Love the project ❤️ 

It seems like Sonarr and Radarr provide their API keys in the response headers for any request as `X-Api-Key`. Is it possible to fetch the API key from the provided endpoint so we don't need to pass it as an environment variable? This would allow for unattended installations.

**Comment by onedr0p** [comment]
You need to pass the apikey inorder to access the API or else it would be insecure and anybody can access your API.

**Comment by ProfessorSalty** [comment]
Access to the API key should be privileged, sure, but as noted [here](https://github.com/Radarr/Radarr/issues/4271#issuecomment-607887940), if you've got access to the UI then you can do anything anyways. Securing access to the key is already a matter of restricting access by using authentication, which Exportarr allows us to use. 

There's also a good argument for not passing sensitive data as an env var since it leaks to all processes with the same level of permission as the docker user. This means that if anyone were to gain access to the system through another container, they could get my API key. It'd be more secure passed as a docker secret or automatically fetched from the header (or even the config file, now that you mention it).

**Comment by onedr0p** [comment]
I think you answered your own question, use Docker secrets or secrets in Kubernetes which I have an example for [here](https://github.com/onedr0p/exportarr/blob/master/examples/kubernetes/radarr-exporter.yaml#L73). 

I have no idea what you mean by getting the APIKey via the header, since you need the API key in-order to use that. Can you show me an example with curl on how to grab the APIkey without auth?

**Comment by onedr0p** [comment]
A little more digging and it looks like you want to be able to parse `initialize.js` and have me parse out the apiKey value in the response?

```
window.Radarr = {
  apiRoot: '/api/v3',
  apiKey: '',
  release: '3.0.0.2853-aphrodite',
  version: '3.0.0.2853',
  branch: 'aphrodite',
  analytics: true,
  userHash: '',
  urlBase: '',
  isProduction: true
};
```

**Comment by ProfessorSalty** [comment]
My apologies, I saw the API key in the response header when I visited the page. Didn't realize that I was looking at an API request. Before lunch, it seemed like any authenticated request would come back with the API key in the header, but on a full stomach I can see that's only with API requests. Sorry, I should have looked at that closer.

Seemed like a great idea at the time!

**Comment by onedr0p** [comment]
I mean you are kind of onto something, the page `initialize.js` does display the APIKey, but I think it's a bit hacky to parse this.

**Comment by PierreMesure** [comment]
I did just that in this [project](https://github.com/Flemmarr/Flemmarr/blob/76364072ca94b41a5104a73f8f4e1cc7ead1127c/src/api.py#L77) and it works great.

I don’t understand why make an API key so easily accessible but since it is, might as well use it.
