### ISSUE TITLE
Include queued metic for Sonarr and Radarr

### ISSUE THREAD

**Issue by ngosang** [onedr0p/exportarr#81]
Lidarr exposes this metric:
* lidarr_queue_total

I think it will be useful to have the same metrics in Sonarr and Radarr.

My config:
* Exportarr v1.1.0
* Sonarr 3.0.8.1507
* Radarr 4.1.0.6175
* Lidarr 1.0.2.2592

**Comment by onedr0p** [comment]
This already exists for Radarr and Sonarr

https://github.com/onedr0p/exportarr/blob/master/cmd/exportarr/main.go#L132
https://github.com/onedr0p/exportarr/blob/master/cmd/exportarr/main.go#L151

https://github.com/onedr0p/exportarr/blob/master/internal/collector/shared/queue.go

**Comment by ngosang** [comment]
Ok, the issue is I can't see the metrics in Grafana because it must be at least one item queued in Sonarr/Radarr to see the metric. They doesn't appear in the metrics endpoint.
Could you set 0 as default value?

https://github.com/onedr0p/exportarr/blob/de5176757f3f4caf313a8e850968245ebaa46659/internal/collector/shared/queue.go#L66

**Comment by onedr0p** [comment]
Probably, but in the meantime you can have grafana treat NULLs as 0

**Comment by onedr0p** [comment]
Going to close this issue as Grafana can be configured to do the above.
