### ISSUE TITLE
Update Grafana Dashboard to include Lidarr

### ISSUE THREAD

**Issue by ngosang** [onedr0p/exportarr#83]
Update Grafana Dashboard to include Sonarr and Lidarr.

Here is mine just in case it's useful for someone.
[grafana_dashboard.txt](https://github.com/onedr0p/exportarr/files/9277119/grafana_dashboard.txt)

![image](https://user-images.githubusercontent.com/10577978/183300271-2bad9f65-f25c-4238-a058-b1c6af75d9e0.png)
![image](https://user-images.githubusercontent.com/10577978/183300289-d17a1b7f-7f19-43f6-8512-713aff5129ee.png)
![image](https://user-images.githubusercontent.com/10577978/183300303-98fe5586-a353-44a8-9034-429643db3492.png)

My config:
* Exportarr v1.1.0
* Sonarr 3.0.8.1507
* Radarr 4.1.0.6175
* Lidarr 1.0.2.2592

**Comment by buzzke** [comment]
Here's mine.  Seperated between Radarr/Sonarr
![image](https://user-images.githubusercontent.com/5507301/192837855-d43fd0ce-8b2f-4d07-a9d8-5baaf8db4829.png)
![image](https://user-images.githubusercontent.com/5507301/192838044-6dfc9622-4fe0-405c-8778-ce26cb842bd3.png)

**Comment by CommanderRedYT** [comment]
> Here's mine. Seperated between Radarr/Sonarr ![image](https://user-images.githubusercontent.com/5507301/192837855-d43fd0ce-8b2f-4d07-a9d8-5baaf8db4829.png) ![image](https://user-images.githubusercontent.com/5507301/192838044-6dfc9622-4fe0-405c-8778-ce26cb842bd3.png)

Care to share the json?

**Comment by rtrox** [comment]
I added a sonarr day to the examples. I don't use LiDAR, but if one of you wants to make a PR for a LiDAR dash I'm glad to pull it in (or share the json and a screenshot and I can make a PR)
