### ISSUE TITLE
exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by rubasace** [onedr0p/exportarr#9]
Since version 0.3.1 I'm getting the following error, also in master:

`standard_init_linux.go:207: exec user process caused "no such file or directory"`

0.3.0 works fine (but I have to specify the port :P). Maybe compiling to a different architecture or something? I'm running in a quite standard `Ubuntu Server 18.04 LTS`

**Comment by onedr0p** [comment]
Probably something changed in the dockerfile. I'll have to review and test. Thanks!

**Comment by onedr0p** [comment]
Can you try onedr0p/exportarr:master once it's done building?

**Comment by rubasace** [comment]
Works like a charm :)

**Comment by onedr0p** [comment]
haha sorry I'll add that back and do a release.

**Comment by onedr0p** [comment]
Should be all set in the lastest version

**Comment by rubasace** [comment]
Amazing! :)
